### ISSUE TITLE
工作流节点的窗口显示无法拖动

### ISSUE THREAD

**Issue by Chow-crypto** [fineplus/fineflow#1]
节点的一些按钮是正常出现在画布中间的，可以拖动。但节点的窗口是出现在左上角的，无法拖动。我的系统是mac m3
<img width="1236" alt="iShot_2024-10-27_17 22 20" src="https://github.com/user-attachments/assets/b55cbf02-062e-4923-ba12-0152448c5f8f">

**Comment by Chow-crypto** [comment]
感谢作者的付出，这项目真的很有用！！！

**Comment by fineplus** [comment]
您好，方便按F12打开控制台截一下错误信息吗？

**Comment by Chow-crypto** [comment]
谢谢，执行pnpm tauri dev后，弹出了应用，问题和在网页上http://localhost:1420/ 看是一样的，而且网页上的左边没有其他节点列表，如网页、工具、代码等。这是我网页上的控制台输出：
<img width="1503" alt="image" src="https://github.com/user-attachments/assets/ef901874-3f8f-4138-868c-258dd5c60f83">

**Comment by Chow-crypto** [comment]
感谢亲自远程修复，太感谢了！已修复。
